### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'country')

### ISSUE THREAD

**Issue by m47een** [ngholson/obs_weather_time_overlay#2]
weatherWidget.html:102 Uncaught TypeError: Cannot read properties of undefined (reading 'country')
    at Object.success (weatherWidget.html:102:27)
    at c (jquery.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery.js:2:29072)
    at l (jquery.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.js:2:82355)

response from API Call is.

{"coord":{"lon":-0.1257,"lat":51.5085},"weather":[{"id":801,"main":"Clouds","description":"few clouds","icon":"02d"}],"base":"stations","main":{"temp":28.54,"feels_like":19.89,"temp_min":23.11,"temp_max":31.95,"pressure":1008,"humidity":92},"visibility":10000,"wind":{"speed":9.22,"deg":230},"clouds":{"all":16},"dt":1670659881,"sys":{"type":2,"id":2075535,"country":"GB","sunrise":1670658898,"sunset":1670687505},"timezone":0,"id":2643743,"name":"London","cod":200}

**Comment by ngholson** [comment]
which API did you sign up with? this will not work with the One Call API 3.0 this requires the Professional collections free API

**Comment by m47een** [comment]
I used the professional collections API

**Comment by ngholson** [comment]
Ok. Thank you for the information. I will check the code this evening.

**Comment by ngholson** [comment]
can you post a copy and paste of the top variable section your weatherwidget.html file please.

**Comment by ngholson** [comment]
I think i have a fix, edit the weatherwidget.html file, on line 102 it should say:

	if (geoResponse[0].country.toLowerCase() != "us") {

change it to read:

	if (geoResponse[0].country.toLowerCase() != "us" || "gb") {

**Comment by m47een** [comment]
I've made the suggested change with no luck.

The API response looks to have moved the country value under the sys section.

**Comment by ngholson** [comment]
Try just using "Stockport" without the UK identifier.

**Comment by ngholson** [comment]
Honestly I think it is the language translator that is erroring out.
Naturally I am at my day job right now. I will do a deeper dive into this
tonight. Thank you for reporting this. I will reply more this evening.

**Comment by ngholson** [comment]
CONFIRMED. 
change:

var yourCity = "Stockport, UK";

to:

var yourCity = "Stockport";

**Comment by m47een** [comment]
Awesome, thank you.

**Comment by m47een** [comment]
Confirmed working. Thank you.
