### ISSUE TITLE
I have tried many ways, but the Chinese name of the city and weather cannot be displayed. What is the problem

### ISSUE THREAD

**Issue by autunn** [ngholson/obs_weather_time_overlay#3]
I have tried many ways, but the Chinese name of the city and weather cannot be displayed. What is the problem

**Comment by ngholson** [comment]
More information is required for this request. please provide information such as city name, translated to english as well as native language in your next request. Thank you.

**Comment by autunn** [comment]
Thanks for your reply, I haven't used this plug-in for a long time, but I think I may still use it in the future, but I don't need a fixed city. I hope this plug-in can automatically locate my city according to my ip. Of course, my current city is Chengdu, China

**Comment by autunn** [comment]
In addition, there is also the question of whether you can make the final displayed page adapt to the browser language, such as Chinese for Chinese users, Japanese for Japanese users, and French for French users
