### ISSUE TITLE
Does not display state or country in the correct language when non 'us'

### ISSUE THREAD

**Issue by kpakur** [ngholson/obs_weather_time_overlay#4]
Steps to reproduce:
Web browser language: "pl-pl"
window.navigator.userLanguage: undefined
window.navigator.language: 'pl'
variable yourCity: Gdańsk, Poland

Actual: Gdańsk, Pomeranian Voivodeship: 7°  bezchmurnie 11:03 PM
Expected: Gdańsk, Pomorskie: 7°  bezchmurnie 11:03 PM
OR expected Gdańsk, Poland: 7°  bezchmurnie 11:03 PM

**Comment by ngholson** [comment]
I do apologize for any issue with the translations, I will look into this, but the translations are handled by a 3rd party API

**Comment by kpakur** [comment]
The problem was not the 3rd party API but how it was called and in particular that a wrong parameter was passed in.
